            - name: Cloudflare R2 Upload
  # You may pin to the exact commit or the version.
  # uses: okkema/github-action-r2@31906225bbae008216d1460f0331fbe6c7886e61
  uses: okkema/github-action-r2@v0.1.1
  with:
    # Cloudflare account id
    account_id: 5cd3c2644a901c67bac45b8a62011d85
    # Cloudflare R2 access key
    r2_access_key: 48e22fe59e204663823342f2c8331beb
    # Cloudflare R2 secret key
    r2_secret_key: eda34b3b9c0bd7a8f1dc48fd5fbe9fc0256e39ddfd32a3a6dfadef3eb20be12e
    # Cloudflare R2 bucket name
    r2_bucket: drool-assets
    # Source directory to upload
    source_dir: /
    # Destination directory for upload
    destination_dir: # optional, default is /
          
