name: Dev Upload to Cloudflare R2
on:
  push:
    branches:
      - dev

jobs:
  upload_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare JS and CSS Files
        run: |
          mkdir temp-files
          cp *.js temp-files/
          cp *.css temp-files/

      - name: Cloudflare R2 Upload
        uses: okkema/github-action-r2@v0.1.1
        with:
          account_id: ${{ secrets.CF_ACCOUNT_ID }}
          r2_access_key: ${{ secrets.R2_ACCESS_KEY }}
          r2_secret_key: ${{ secrets.R2_SECRET_KEY }}
          r2_bucket: drool-assets
          source_dir: temp-files/
          destination_dir: code-dev
